-- ================================================================
-- BNK 부산은행 금융 상품 플랫폼
-- [도메인 01] 공통 코드 · 관리자
-- Oracle 21c
-- 포함 테이블:
--   COMMON_CODE_GROUPS, COMMON_CODES
--   ADMIN_USERS, ADMIN_ROLES, ADMIN_PERMISSIONS
--   ROLE_PERMISSIONS, ADMIN_USER_ROLES
-- ================================================================


-- ================================================================
-- [SECTION 1] DROP (재실행 대비 — 의존 순서 역순)
-- ================================================================

BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_ADMIN_USER_ROLES_BI';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_ROLE_PERMISSIONS_BI';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_ADMIN_PERMISSIONS_BI';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_ADMIN_ROLES_BI';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_ADMIN_USERS_BI';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_COMMON_CODES_BI';        EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE ADMIN_USER_ROLES    CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ROLE_PERMISSIONS    CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ADMIN_PERMISSIONS   CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ADMIN_ROLES         CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ADMIN_USERS         CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE COMMON_CODES        CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE COMMON_CODE_GROUPS  CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ADMIN_USER_ROLES';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ROLE_PERMISSIONS';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ADMIN_PERMISSIONS';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ADMIN_ROLES';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ADMIN_USERS';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COMMON_CODES';       EXCEPTION WHEN OTHERS THEN NULL; END;
/


-- ================================================================
-- [SECTION 2] CREATE
-- ================================================================

-- ── 시퀀스 ────────────────────────────────────────────────────────
CREATE SEQUENCE SEQ_COMMON_CODES      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ADMIN_USERS       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ADMIN_ROLES       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ADMIN_PERMISSIONS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ROLE_PERMISSIONS  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ADMIN_USER_ROLES  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


-- ── 테이블 ────────────────────────────────────────────────────────

-- 01. COMMON_CODE_GROUPS
CREATE TABLE COMMON_CODE_GROUPS (
    group_code      VARCHAR2(50)   PRIMARY KEY,
    group_name      VARCHAR2(100)  NOT NULL,
    description     VARCHAR2(1000),
    use_yn          CHAR(1)        DEFAULT 'Y' CHECK (use_yn IN ('Y','N')),
    created_at      TIMESTAMP      DEFAULT SYSTIMESTAMP,
    created_by      NUMBER(10),
    updated_at      TIMESTAMP,
    updated_by      NUMBER(10)
);
COMMENT ON TABLE COMMON_CODE_GROUPS IS '공통 코드 그룹';

-- 02. COMMON_CODES
CREATE TABLE COMMON_CODES (
    code_id         NUMBER(10)     PRIMARY KEY,
    group_code      VARCHAR2(50)   NOT NULL,
    code            VARCHAR2(50)   NOT NULL,
    code_name       VARCHAR2(100)  NOT NULL,
    code_value      VARCHAR2(200),
    display_order   NUMBER(5),
    description     VARCHAR2(1000),
    use_yn          CHAR(1)        DEFAULT 'Y' CHECK (use_yn IN ('Y','N')),
    created_at      TIMESTAMP      DEFAULT SYSTIMESTAMP,
    created_by      NUMBER(10),
    updated_at      TIMESTAMP,
    updated_by      NUMBER(10),
    deleted_yn      CHAR(1)        DEFAULT 'N' CHECK (deleted_yn IN ('Y','N')),
    deleted_at      TIMESTAMP,
    CONSTRAINT FK_COMMON_CODES_GROUP FOREIGN KEY (group_code) REFERENCES COMMON_CODE_GROUPS(group_code)
);
COMMENT ON TABLE COMMON_CODES IS '공통 코드 상세';

-- 03. ADMIN_USERS
CREATE TABLE ADMIN_USERS (
    admin_id            NUMBER(10)     PRIMARY KEY,
    username            VARCHAR2(50)   NOT NULL UNIQUE,
    password_hash       VARCHAR2(255)  NOT NULL,
    name                VARCHAR2(50)   NOT NULL,
    email               VARCHAR2(100),
    phone               VARCHAR2(20),
    status_code         VARCHAR2(50)   DEFAULT 'ACTIVE',
    login_fail_count    NUMBER(5)      DEFAULT 0,
    locked_until        TIMESTAMP,
    last_login_at       TIMESTAMP,
    created_at          TIMESTAMP      DEFAULT SYSTIMESTAMP,
    created_by          NUMBER(10),
    updated_at          TIMESTAMP,
    updated_by          NUMBER(10),
    deleted_yn          CHAR(1)        DEFAULT 'N' CHECK (deleted_yn IN ('Y','N')),
    deleted_at          TIMESTAMP
);
COMMENT ON TABLE ADMIN_USERS IS '관리자 계정';

-- 04. ADMIN_ROLES
CREATE TABLE ADMIN_ROLES (
    role_id         NUMBER(10)     PRIMARY KEY,
    role_code       VARCHAR2(50)   NOT NULL UNIQUE,
    role_name       VARCHAR2(100)  NOT NULL,
    description     VARCHAR2(1000),
    created_at      TIMESTAMP      DEFAULT SYSTIMESTAMP,
    created_by      NUMBER(10),
    updated_at      TIMESTAMP,
    updated_by      NUMBER(10),
    deleted_yn      CHAR(1)        DEFAULT 'N' CHECK (deleted_yn IN ('Y','N')),
    deleted_at      TIMESTAMP
);
COMMENT ON TABLE ADMIN_ROLES IS '관리자 역할';

-- 05. ADMIN_PERMISSIONS
CREATE TABLE ADMIN_PERMISSIONS (
    permission_id   NUMBER(10)     PRIMARY KEY,
    permission_code VARCHAR2(100)  NOT NULL UNIQUE,
    permission_name VARCHAR2(200)  NOT NULL,
    description     VARCHAR2(1000),
    created_at      TIMESTAMP      DEFAULT SYSTIMESTAMP,
    deleted_yn      CHAR(1)        DEFAULT 'N' CHECK (deleted_yn IN ('Y','N'))
);
COMMENT ON TABLE ADMIN_PERMISSIONS IS '관리자 권한 항목';

-- 06. ROLE_PERMISSIONS
CREATE TABLE ROLE_PERMISSIONS (
    role_permission_id  NUMBER(10)  PRIMARY KEY,
    role_id             NUMBER(10)  NOT NULL,
    permission_id       NUMBER(10)  NOT NULL,
    created_at          TIMESTAMP   DEFAULT SYSTIMESTAMP,
    deleted_yn          CHAR(1)     DEFAULT 'N' CHECK (deleted_yn IN ('Y','N')),
    CONSTRAINT FK_ROLE_PERM_ROLE  FOREIGN KEY (role_id)       REFERENCES ADMIN_ROLES(role_id),
    CONSTRAINT FK_ROLE_PERM_PERM  FOREIGN KEY (permission_id) REFERENCES ADMIN_PERMISSIONS(permission_id)
);
COMMENT ON TABLE ROLE_PERMISSIONS IS '역할-권한 매핑';

-- 07. ADMIN_USER_ROLES
CREATE TABLE ADMIN_USER_ROLES (
    admin_user_role_id  NUMBER(10)  PRIMARY KEY,
    admin_id            NUMBER(10)  NOT NULL,
    role_id             NUMBER(10)  NOT NULL,
    assigned_at         TIMESTAMP   DEFAULT SYSTIMESTAMP,
    assigned_by         NUMBER(10),
    deleted_yn          CHAR(1)     DEFAULT 'N' CHECK (deleted_yn IN ('Y','N')),
    CONSTRAINT FK_ADMIN_USER_ROLE_ADMIN FOREIGN KEY (admin_id) REFERENCES ADMIN_USERS(admin_id),
    CONSTRAINT FK_ADMIN_USER_ROLE_ROLE  FOREIGN KEY (role_id)  REFERENCES ADMIN_ROLES(role_id)
);
COMMENT ON TABLE ADMIN_USER_ROLES IS '관리자-역할 매핑';


-- ── 트리거 (BEFORE INSERT — PK 자동 채번) ─────────────────────────
CREATE OR REPLACE TRIGGER TRG_COMMON_CODES_BI
BEFORE INSERT ON COMMON_CODES FOR EACH ROW WHEN (NEW.code_id IS NULL)
BEGIN :NEW.code_id := SEQ_COMMON_CODES.NEXTVAL; END TRG_COMMON_CODES_BI;
/

CREATE OR REPLACE TRIGGER TRG_ADMIN_USERS_BI
BEFORE INSERT ON ADMIN_USERS FOR EACH ROW WHEN (NEW.admin_id IS NULL)
BEGIN :NEW.admin_id := SEQ_ADMIN_USERS.NEXTVAL; END TRG_ADMIN_USERS_BI;
/

CREATE OR REPLACE TRIGGER TRG_ADMIN_ROLES_BI
BEFORE INSERT ON ADMIN_ROLES FOR EACH ROW WHEN (NEW.role_id IS NULL)
BEGIN :NEW.role_id := SEQ_ADMIN_ROLES.NEXTVAL; END TRG_ADMIN_ROLES_BI;
/

CREATE OR REPLACE TRIGGER TRG_ADMIN_PERMISSIONS_BI
BEFORE INSERT ON ADMIN_PERMISSIONS FOR EACH ROW WHEN (NEW.permission_id IS NULL)
BEGIN :NEW.permission_id := SEQ_ADMIN_PERMISSIONS.NEXTVAL; END TRG_ADMIN_PERMISSIONS_BI;
/

CREATE OR REPLACE TRIGGER TRG_ROLE_PERMISSIONS_BI
BEFORE INSERT ON ROLE_PERMISSIONS FOR EACH ROW WHEN (NEW.role_permission_id IS NULL)
BEGIN :NEW.role_permission_id := SEQ_ROLE_PERMISSIONS.NEXTVAL; END TRG_ROLE_PERMISSIONS_BI;
/

CREATE OR REPLACE TRIGGER TRG_ADMIN_USER_ROLES_BI
BEFORE INSERT ON ADMIN_USER_ROLES FOR EACH ROW WHEN (NEW.admin_user_role_id IS NULL)
BEGIN :NEW.admin_user_role_id := SEQ_ADMIN_USER_ROLES.NEXTVAL; END TRG_ADMIN_USER_ROLES_BI;
/


-- ── 인덱스 ────────────────────────────────────────────────────────
-- (COMMON_CODE_GROUPS.group_code는 PK이므로 별도 인덱스 불필요)
CREATE INDEX IDX_COMMON_CODES_GROUP    ON COMMON_CODES(group_code);
CREATE INDEX IDX_ADMIN_USERS_STATUS    ON ADMIN_USERS(status_code);
CREATE INDEX IDX_ROLE_PERM_ROLE        ON ROLE_PERMISSIONS(role_id);
CREATE INDEX IDX_ADMIN_USER_ROLE_ADMIN ON ADMIN_USER_ROLES(admin_id);


COMMIT;
