-- ================================================================
-- BNK 부산은행 금융 상품 플랫폼
-- [도메인 04] 약관
-- Oracle 21c
-- 포함 테이블:
--   TERMS_GROUPS, TERMS_PACKAGES, PACKAGE_TERMS
--   TERMS_MASTERS (required_yn, display_order ALTER 통합)
--   TERMS, TERMS_STATUS_HISTORY, TERMS_EXPOSURE_RULES, TERMS_FILES
--   CARD_TERMS, CARD_NOTICE_SECTIONS
--   USER_TERMS_AGREEMENTS (credit_app_id / check_app_id는 05번 파일에서 ALTER)
--   TERMS_CHANGE_DIFFS, TERMS_NOTIFICATION_HISTORY
-- ================================================================


-- ================================================================
-- [SECTION 1] DROP (재실행 대비)
-- ================================================================

BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_TERMS_NOTIF_HIST_BI';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_TERMS_CHANGE_DIFFS_BI';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_CARD_NOTICE_BI';               EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_USER_TERMS_AGMT_BI';           EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_CARD_TERMS_BI';                EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_TERMS_FILES_BI';               EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_TERMS_EXPOSURE_RULES_BI';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_TERMS_STATUS_HIST_BI';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_TERMS_BI';                     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_TERMS_MASTERS_BI';             EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_PACKAGE_TERMS_BI';             EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_TERMS_PACKAGES_BI';            EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_TERMS_GROUPS_BI';              EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE TERMS_NOTIFICATION_HISTORY CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TERMS_CHANGE_DIFFS        CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USER_TERMS_AGREEMENTS     CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CARD_NOTICE_SECTIONS      CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CARD_TERMS                CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TERMS_FILES               CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TERMS_EXPOSURE_RULES      CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TERMS_STATUS_HISTORY      CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TERMS                     CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TERMS_MASTERS             CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PACKAGE_TERMS             CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TERMS_PACKAGES            CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TERMS_GROUPS              CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TERMS_NOTIFICATION_HISTORY'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TERMS_CHANGE_DIFFS';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_USER_TERMS_AGREEMENTS';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CARD_NOTICE_SECTIONS';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CARD_TERMS';                 EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TERMS_FILES';                EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TERMS_EXPOSURE_RULES';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TERMS_STATUS_HISTORY';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TERMS';                      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TERMS_MASTERS';              EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PACKAGE_TERMS';              EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TERMS_PACKAGES';             EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TERMS_GROUPS';               EXCEPTION WHEN OTHERS THEN NULL; END;
/


-- ================================================================
-- [SECTION 2] CREATE
-- ================================================================

-- ── 시퀀스 ────────────────────────────────────────────────────────
CREATE SEQUENCE SEQ_TERMS_GROUPS              START WITH 1   INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TERMS_PACKAGES            START WITH 1   INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PACKAGE_TERMS             START WITH 1   INCREMENT BY 1 NOCACHE NOCYCLE;
-- [주의] 더미데이터 terms_master_id 최대값 125 → START WITH 126으로 설정
CREATE SEQUENCE SEQ_TERMS_MASTERS             START WITH 126 INCREMENT BY 1 NOCACHE NOCYCLE;
-- [주의] 더미데이터 terms_id 최대값 125 → START WITH 126으로 설정
CREATE SEQUENCE SEQ_TERMS                     START WITH 126 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TERMS_STATUS_HISTORY      START WITH 1   INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TERMS_EXPOSURE_RULES      START WITH 1   INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TERMS_FILES               START WITH 1   INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CARD_TERMS                START WITH 1   INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_USER_TERMS_AGREEMENTS     START WITH 1   INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CARD_NOTICE_SECTIONS      START WITH 1   INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TERMS_CHANGE_DIFFS        START WITH 1   INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TERMS_NOTIFICATION_HISTORY START WITH 1  INCREMENT BY 1 NOCACHE NOCYCLE;


-- ── 테이블 ────────────────────────────────────────────────────────

-- 29. TERMS_GROUPS
CREATE TABLE TERMS_GROUPS (
    group_id        NUMBER(10)     PRIMARY KEY,
    group_name      VARCHAR2(100)  NOT NULL,
    group_type      VARCHAR2(30)   NOT NULL,
    display_order   NUMBER(5),
    created_at      TIMESTAMP      DEFAULT SYSTIMESTAMP
);
COMMENT ON TABLE  TERMS_GROUPS            IS '약관 그룹 관리';
COMMENT ON COLUMN TERMS_GROUPS.group_type IS 'REQUIRED / OPTIONAL / NOTICE';

-- 30. TERMS_PACKAGES
CREATE TABLE TERMS_PACKAGES (
    package_id      NUMBER(10)     PRIMARY KEY,
    package_name    VARCHAR2(200)  NOT NULL,
    package_type    VARCHAR2(50)   NOT NULL,
    description     VARCHAR2(1000),
    created_at      TIMESTAMP      DEFAULT SYSTIMESTAMP
);
COMMENT ON TABLE  TERMS_PACKAGES              IS '약관 패키지 관리';
COMMENT ON COLUMN TERMS_PACKAGES.package_type IS 'SIGNUP / CARD_APPLY / ACCOUNT_OPEN / EVENT';

-- 31. TERMS_MASTERS
-- [최종 상태: required_yn, display_order ALTER 통합]
CREATE TABLE TERMS_MASTERS (
    terms_master_id  NUMBER(10)    PRIMARY KEY,
    terms_type       VARCHAR2(50)  NOT NULL,
    title            VARCHAR2(300) NOT NULL,
    description      VARCHAR2(1000),
    required_yn      CHAR(1)       DEFAULT 'N' CHECK (required_yn IN ('Y','N')),
    display_order    NUMBER(5)     DEFAULT 1,
    created_at       TIMESTAMP     DEFAULT SYSTIMESTAMP
);
COMMENT ON TABLE  TERMS_MASTERS              IS '약관 원본 정의 (버전 공통 메타)';
COMMENT ON COLUMN TERMS_MASTERS.terms_type   IS 'COMMON / PRIVACY / CARD_SERVICE';
COMMENT ON COLUMN TERMS_MASTERS.required_yn  IS '필수 약관 여부';

-- 32. TERMS (버전 관리)
CREATE TABLE TERMS (
    terms_id                NUMBER(10)     PRIMARY KEY,
    terms_master_id         NUMBER(10)     NOT NULL,
    version                 VARCHAR2(20)   NOT NULL,
    content_html            CLOB,
    required_yn             CHAR(1)        DEFAULT 'Y' CHECK (required_yn          IN ('Y','N')),
    reconsent_required_yn   CHAR(1)        DEFAULT 'N' CHECK (reconsent_required_yn IN ('Y','N')),
    status                  VARCHAR2(30)   DEFAULT 'DRAFT'
                                CHECK (status IN ('DRAFT','REVIEW','APPROVED','PUBLISHED','EXPIRED')),
    effective_from          DATE           NOT NULL,
    effective_to            DATE,
    document_hash           VARCHAR2(256),
    internal_note           VARCHAR2(2000),
    approved_by             NUMBER(10),
    approved_at             TIMESTAMP,
    created_at              TIMESTAMP      DEFAULT SYSTIMESTAMP,
    updated_at              TIMESTAMP,
    CONSTRAINT FK_TERMS_MASTER FOREIGN KEY (terms_master_id) REFERENCES TERMS_MASTERS(terms_master_id)
);
COMMENT ON TABLE  TERMS        IS '약관 버전 관리';
COMMENT ON COLUMN TERMS.status IS 'DRAFT → REVIEW → APPROVED → PUBLISHED → EXPIRED';

-- 33. PACKAGE_TERMS
CREATE TABLE PACKAGE_TERMS (
    package_terms_id  NUMBER(10)  PRIMARY KEY,
    package_id        NUMBER(10)  NOT NULL,
    terms_id          NUMBER(10)  NOT NULL,
    display_order     NUMBER(5),
    created_at        TIMESTAMP   DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_PACKAGE_TERMS_PACKAGE FOREIGN KEY (package_id) REFERENCES TERMS_PACKAGES(package_id),
    CONSTRAINT FK_PACKAGE_TERMS_TERMS   FOREIGN KEY (terms_id)   REFERENCES TERMS(terms_id)
);
COMMENT ON TABLE PACKAGE_TERMS IS '패키지 구성 약관';

-- 34. TERMS_STATUS_HISTORY
CREATE TABLE TERMS_STATUS_HISTORY (
    history_id       NUMBER(10)    PRIMARY KEY,
    terms_id         NUMBER(10)    NOT NULL,
    previous_status  VARCHAR2(30),
    changed_status   VARCHAR2(30)  NOT NULL,
    changed_by       NUMBER(10),
    changed_reason   VARCHAR2(1000),
    changed_at       TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_TERMS_STATUS_HISTORY FOREIGN KEY (terms_id) REFERENCES TERMS(terms_id)
);
COMMENT ON TABLE TERMS_STATUS_HISTORY IS '약관 상태 변경 이력';

-- 35. TERMS_EXPOSURE_RULES
CREATE TABLE TERMS_EXPOSURE_RULES (
    rule_id     NUMBER(10)     PRIMARY KEY,
    terms_id    NUMBER(10)     NOT NULL,
    rule_type   VARCHAR2(50)   NOT NULL,
    rule_value  VARCHAR2(1000) NOT NULL,
    created_at  TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_EXPOSURE_TERMS FOREIGN KEY (terms_id) REFERENCES TERMS(terms_id)
);
COMMENT ON TABLE  TERMS_EXPOSURE_RULES           IS '약관 노출 정책';
COMMENT ON COLUMN TERMS_EXPOSURE_RULES.rule_type IS 'AGE_MIN / CARD_TYPE / CARD_BRAND';

-- 36. TERMS_FILES
CREATE TABLE TERMS_FILES (
    file_id         NUMBER(10)     PRIMARY KEY,
    terms_id        NUMBER(10)     NOT NULL,
    file_type       VARCHAR2(30)   NOT NULL,
    file_path       VARCHAR2(1000) NOT NULL,
    original_name   VARCHAR2(300)  NOT NULL,
    stored_name     VARCHAR2(300),
    file_extension  VARCHAR2(20),
    file_size       NUMBER(15),
    mime_type       VARCHAR2(100),
    is_primary      CHAR(1)        DEFAULT 'N' CHECK (is_primary    IN ('Y','N')),
    download_count  NUMBER(10)     DEFAULT 0,
    virus_scan_yn   CHAR(1)        DEFAULT 'N' CHECK (virus_scan_yn IN ('Y','N')),
    uploaded_at     TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_TERMS_FILES_TERMS FOREIGN KEY (terms_id) REFERENCES TERMS(terms_id)
);
COMMENT ON TABLE  TERMS_FILES           IS '약관 첨부파일';
COMMENT ON COLUMN TERMS_FILES.file_type IS 'PDF / IMAGE / SUMMARY';

-- 37. CARD_TERMS
CREATE TABLE CARD_TERMS (
    card_terms_id           NUMBER(10)  PRIMARY KEY,
    card_id                 NUMBER(10)  NOT NULL,
    terms_id                NUMBER(10)  NOT NULL,
    group_id                NUMBER(10),
    required_yn             CHAR(1)     DEFAULT 'Y' CHECK (required_yn IN ('Y','N')),
    exposure_condition_json CLOB,
    display_order           NUMBER(5),
    created_at              TIMESTAMP   DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_CARD_TERMS_CARD   FOREIGN KEY (card_id)  REFERENCES CARDS(card_id),
    CONSTRAINT FK_CARD_TERMS_TERMS  FOREIGN KEY (terms_id) REFERENCES TERMS(terms_id),
    CONSTRAINT FK_CARD_TERMS_GROUP  FOREIGN KEY (group_id) REFERENCES TERMS_GROUPS(group_id)
);
COMMENT ON TABLE CARD_TERMS IS '카드별 약관 연결';

-- 38. USER_TERMS_AGREEMENTS
-- [주의] credit_app_id, check_app_id 컬럼은
--        05_ddl_card_application.sql에서 ALTER TABLE로 추가됨
CREATE TABLE USER_TERMS_AGREEMENTS (
    agreement_id            NUMBER(10)     PRIMARY KEY,
    user_id                 NUMBER(10)     NOT NULL,
    terms_id                NUMBER(10)     NOT NULL,
    agreed_yn               CHAR(1)        DEFAULT 'Y' CHECK (agreed_yn IN ('Y','N')),
    agreement_action        VARCHAR2(30)   DEFAULT 'AGREE',
    agreed_version          VARCHAR2(20)   NOT NULL,
    agreement_channel       VARCHAR2(30),
    agreement_source        VARCHAR2(50),
    agreed_content_snapshot CLOB,
    agreed_at               TIMESTAMP      DEFAULT SYSTIMESTAMP,
    ip_address              VARCHAR2(100),
    user_agent              VARCHAR2(1000),
    CONSTRAINT FK_USER_TERMS_USER  FOREIGN KEY (user_id)  REFERENCES USERS(user_id),
    CONSTRAINT FK_USER_TERMS_TERMS FOREIGN KEY (terms_id) REFERENCES TERMS(terms_id)
);
COMMENT ON TABLE  USER_TERMS_AGREEMENTS                    IS '사용자 약관 동의 이력';
COMMENT ON COLUMN USER_TERMS_AGREEMENTS.agreement_action   IS 'AGREE / WITHDRAW / REAGREE';
COMMENT ON COLUMN USER_TERMS_AGREEMENTS.agreement_channel  IS 'WEB / MOBILE / ADMIN / CALL_CENTER';
COMMENT ON COLUMN USER_TERMS_AGREEMENTS.agreement_source   IS 'SIGNUP / CREDIT_CARD_APPLY / CHECK_CARD_APPLY / ACCOUNT_OPEN / EVENT';

-- 39. CARD_NOTICE_SECTIONS
CREATE TABLE CARD_NOTICE_SECTIONS (
    notice_id       NUMBER(10)     PRIMARY KEY,
    card_id         NUMBER(10)     NOT NULL,
    section_title   VARCHAR2(200)  NOT NULL,
    content_html    CLOB,
    display_order   NUMBER(5),
    created_at      TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_NOTICE_CARD FOREIGN KEY (card_id) REFERENCES CARDS(card_id)
);
COMMENT ON TABLE CARD_NOTICE_SECTIONS IS '카드 상품 안내/유의사항';

-- 40. TERMS_CHANGE_DIFFS
CREATE TABLE TERMS_CHANGE_DIFFS (
    diff_id         NUMBER(10)  PRIMARY KEY,
    old_terms_id    NUMBER(10)  NOT NULL,
    new_terms_id    NUMBER(10)  NOT NULL,
    summary_html    CLOB        NOT NULL,
    created_at      TIMESTAMP   DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_DIFF_OLD_TERMS FOREIGN KEY (old_terms_id) REFERENCES TERMS(terms_id),
    CONSTRAINT FK_DIFF_NEW_TERMS FOREIGN KEY (new_terms_id) REFERENCES TERMS(terms_id)
);
COMMENT ON TABLE TERMS_CHANGE_DIFFS IS '약관 변경 비교';

-- 41. TERMS_NOTIFICATION_HISTORY
CREATE TABLE TERMS_NOTIFICATION_HISTORY (
    notification_id       NUMBER(10)     PRIMARY KEY,
    user_id               NUMBER(10)     NOT NULL,
    terms_id              NUMBER(10)     NOT NULL,
    notification_type     VARCHAR2(30)   NOT NULL,
    notification_title    VARCHAR2(300),
    notification_message  VARCHAR2(2000),
    sent_yn               CHAR(1)        DEFAULT 'N' CHECK (sent_yn IN ('Y','N')),
    sent_at               TIMESTAMP,
    read_yn               CHAR(1)        DEFAULT 'N' CHECK (read_yn IN ('Y','N')),
    read_at               TIMESTAMP,
    created_at            TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_NOTIFICATION_USER  FOREIGN KEY (user_id)  REFERENCES USERS(user_id),
    CONSTRAINT FK_NOTIFICATION_TERMS FOREIGN KEY (terms_id) REFERENCES TERMS(terms_id)
);
COMMENT ON TABLE  TERMS_NOTIFICATION_HISTORY                    IS '약관 알림 발송 이력';
COMMENT ON COLUMN TERMS_NOTIFICATION_HISTORY.notification_type  IS 'EMAIL / SMS / PUSH / INAPP';


-- ── 트리거 ────────────────────────────────────────────────────────
CREATE OR REPLACE TRIGGER TRG_TERMS_GROUPS_BI
BEFORE INSERT ON TERMS_GROUPS FOR EACH ROW WHEN (NEW.group_id IS NULL)
BEGIN :NEW.group_id := SEQ_TERMS_GROUPS.NEXTVAL; END TRG_TERMS_GROUPS_BI;
/

CREATE OR REPLACE TRIGGER TRG_TERMS_PACKAGES_BI
BEFORE INSERT ON TERMS_PACKAGES FOR EACH ROW WHEN (NEW.package_id IS NULL)
BEGIN :NEW.package_id := SEQ_TERMS_PACKAGES.NEXTVAL; END TRG_TERMS_PACKAGES_BI;
/

CREATE OR REPLACE TRIGGER TRG_TERMS_MASTERS_BI
BEFORE INSERT ON TERMS_MASTERS FOR EACH ROW WHEN (NEW.terms_master_id IS NULL)
BEGIN :NEW.terms_master_id := SEQ_TERMS_MASTERS.NEXTVAL; END TRG_TERMS_MASTERS_BI;
/

CREATE OR REPLACE TRIGGER TRG_TERMS_BI
BEFORE INSERT ON TERMS FOR EACH ROW WHEN (NEW.terms_id IS NULL)
BEGIN :NEW.terms_id := SEQ_TERMS.NEXTVAL; END TRG_TERMS_BI;
/

CREATE OR REPLACE TRIGGER TRG_PACKAGE_TERMS_BI
BEFORE INSERT ON PACKAGE_TERMS FOR EACH ROW WHEN (NEW.package_terms_id IS NULL)
BEGIN :NEW.package_terms_id := SEQ_PACKAGE_TERMS.NEXTVAL; END TRG_PACKAGE_TERMS_BI;
/

CREATE OR REPLACE TRIGGER TRG_TERMS_STATUS_HIST_BI
BEFORE INSERT ON TERMS_STATUS_HISTORY FOR EACH ROW WHEN (NEW.history_id IS NULL)
BEGIN :NEW.history_id := SEQ_TERMS_STATUS_HISTORY.NEXTVAL; END TRG_TERMS_STATUS_HIST_BI;
/

CREATE OR REPLACE TRIGGER TRG_TERMS_EXPOSURE_RULES_BI
BEFORE INSERT ON TERMS_EXPOSURE_RULES FOR EACH ROW WHEN (NEW.rule_id IS NULL)
BEGIN :NEW.rule_id := SEQ_TERMS_EXPOSURE_RULES.NEXTVAL; END TRG_TERMS_EXPOSURE_RULES_BI;
/

CREATE OR REPLACE TRIGGER TRG_TERMS_FILES_BI
BEFORE INSERT ON TERMS_FILES FOR EACH ROW WHEN (NEW.file_id IS NULL)
BEGIN :NEW.file_id := SEQ_TERMS_FILES.NEXTVAL; END TRG_TERMS_FILES_BI;
/

CREATE OR REPLACE TRIGGER TRG_CARD_TERMS_BI
BEFORE INSERT ON CARD_TERMS FOR EACH ROW WHEN (NEW.card_terms_id IS NULL)
BEGIN :NEW.card_terms_id := SEQ_CARD_TERMS.NEXTVAL; END TRG_CARD_TERMS_BI;
/

CREATE OR REPLACE TRIGGER TRG_USER_TERMS_AGMT_BI
BEFORE INSERT ON USER_TERMS_AGREEMENTS FOR EACH ROW WHEN (NEW.agreement_id IS NULL)
BEGIN :NEW.agreement_id := SEQ_USER_TERMS_AGREEMENTS.NEXTVAL; END TRG_USER_TERMS_AGMT_BI;
/

CREATE OR REPLACE TRIGGER TRG_CARD_NOTICE_BI
BEFORE INSERT ON CARD_NOTICE_SECTIONS FOR EACH ROW WHEN (NEW.notice_id IS NULL)
BEGIN :NEW.notice_id := SEQ_CARD_NOTICE_SECTIONS.NEXTVAL; END TRG_CARD_NOTICE_BI;
/

CREATE OR REPLACE TRIGGER TRG_TERMS_CHANGE_DIFFS_BI
BEFORE INSERT ON TERMS_CHANGE_DIFFS FOR EACH ROW WHEN (NEW.diff_id IS NULL)
BEGIN :NEW.diff_id := SEQ_TERMS_CHANGE_DIFFS.NEXTVAL; END TRG_TERMS_CHANGE_DIFFS_BI;
/

CREATE OR REPLACE TRIGGER TRG_TERMS_NOTIF_HIST_BI
BEFORE INSERT ON TERMS_NOTIFICATION_HISTORY FOR EACH ROW WHEN (NEW.notification_id IS NULL)
BEGIN :NEW.notification_id := SEQ_TERMS_NOTIFICATION_HISTORY.NEXTVAL; END TRG_TERMS_NOTIF_HIST_BI;
/


-- ── 인덱스 ────────────────────────────────────────────────────────
CREATE INDEX IDX_TERMS_STATUS       ON TERMS(status);
CREATE INDEX IDX_TERMS_MASTER       ON TERMS(terms_master_id);
CREATE INDEX IDX_USER_TERMS_USER    ON USER_TERMS_AGREEMENTS(user_id);
CREATE INDEX IDX_USER_TERMS_TERMS   ON USER_TERMS_AGREEMENTS(terms_id);
CREATE INDEX IDX_CARD_TERMS_CARD    ON CARD_TERMS(card_id);
CREATE INDEX IDX_TERMS_STATUS_HIST  ON TERMS_STATUS_HISTORY(terms_id);


COMMIT;
