-- ================================================================
-- BNK 부산은행 금융 상품 플랫폼
-- [도메인 06] 파일 · 검색 · AI · 이벤트로그 · 행위로그
-- Oracle 21c
-- 포함 테이블:
--   FILE_UPLOADS
--   SEARCH_KEYWORDS, CARD_KEYWORDS, SEARCH_LOGS
--   USER_SPENDING_PATTERNS, AI_CHAT_LOGS
--   EVENT_LOGS (부모), CARD_EVENT_LOGS, TERMS_EVENT_LOGS, CHAT_EVENT_LOGS
--   USER_ACTIVITY_LOG, ADMIN_ACTIVITY_LOG
-- ================================================================


-- ================================================================
-- [SECTION 1] DROP (재실행 대비)
-- ================================================================

BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_ADMIN_ACTIVITY_LOG_NO_UPD'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_ADMIN_ACTIVITY_LOG_NO_DEL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_ADMIN_ACTIVITY_LOG_BI';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_USER_ACTIVITY_LOG_NO_UPD';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_USER_ACTIVITY_LOG_NO_DEL';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_USER_ACTIVITY_LOG_BI';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_EVENT_LOGS_BI';             EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_AI_CHAT_LOGS_BI';           EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_USER_SPENDING_BI';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_SEARCH_LOGS_BI';            EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_CARD_KEYWORDS_BI';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_SEARCH_KEYWORDS_BI';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_FILE_UPLOADS_BI';           EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE ADMIN_ACTIVITY_LOG CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USER_ACTIVITY_LOG  CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHAT_EVENT_LOGS    CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TERMS_EVENT_LOGS   CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CARD_EVENT_LOGS    CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EVENT_LOGS         CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE AI_CHAT_LOGS       CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USER_SPENDING_PATTERNS CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SEARCH_LOGS        CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CARD_KEYWORDS      CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SEARCH_KEYWORDS    CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FILE_UPLOADS       CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ADMIN_ACTIVITY_LOG';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_USER_ACTIVITY_LOG';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EVENT_LOGS';            EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_AI_CHAT_LOGS';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_USER_SPENDING_PATTERNS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_SEARCH_LOGS';           EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CARD_KEYWORDS';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_SEARCH_KEYWORDS';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_FILE_UPLOADS';          EXCEPTION WHEN OTHERS THEN NULL; END;
/


-- ================================================================
-- [SECTION 2] CREATE
-- ================================================================

-- ── 시퀀스 ────────────────────────────────────────────────────────
CREATE SEQUENCE SEQ_FILE_UPLOADS           START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SEARCH_KEYWORDS        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CARD_KEYWORDS          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SEARCH_LOGS            START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_USER_SPENDING_PATTERNS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_AI_CHAT_LOGS           START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EVENT_LOGS             START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_USER_ACTIVITY_LOG      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ADMIN_ACTIVITY_LOG     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


-- ── 테이블 ────────────────────────────────────────────────────────

-- 42. FILE_UPLOADS
CREATE TABLE FILE_UPLOADS (
    file_id              NUMBER(10)     PRIMARY KEY,
    original_filename    VARCHAR2(500)  NOT NULL,
    stored_filename      VARCHAR2(500)  NOT NULL,
    stored_path          VARCHAR2(1000) NOT NULL,
    file_url             VARCHAR2(1000),
    file_type_code       VARCHAR2(50)   NOT NULL,
    mime_type            VARCHAR2(100),
    file_size            NUMBER(15),
    converted_file_id    NUMBER(10),
    convert_status_code  VARCHAR2(50),
    ref_type_code        VARCHAR2(50),
    ref_id               NUMBER(10),
    created_at           TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    created_by           NUMBER(10),
    deleted_yn           CHAR(1)        DEFAULT 'N' NOT NULL CHECK (deleted_yn IN ('Y','N')),
    deleted_at           TIMESTAMP,
    CONSTRAINT FK_FU_CONVERTED_FILE FOREIGN KEY (converted_file_id) REFERENCES FILE_UPLOADS(file_id),
    CONSTRAINT FK_FU_CREATED_BY     FOREIGN KEY (created_by)        REFERENCES ADMIN_USERS(admin_id)
);
COMMENT ON TABLE FILE_UPLOADS IS '파일 업로드 관리';

-- 43. SEARCH_KEYWORDS
CREATE TABLE SEARCH_KEYWORDS (
    keyword_id     NUMBER(10)     PRIMARY KEY,
    keyword        VARCHAR2(100)  NOT NULL UNIQUE,
    category_id    NUMBER(10),
    use_yn         CHAR(1)        DEFAULT 'Y' NOT NULL CHECK (use_yn    IN ('Y','N')),
    display_order  NUMBER(5),
    created_at     TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    created_by     NUMBER(10),
    updated_at     TIMESTAMP,
    updated_by     NUMBER(10),
    deleted_yn     CHAR(1)        DEFAULT 'N' NOT NULL CHECK (deleted_yn IN ('Y','N')),
    deleted_at     TIMESTAMP,
    CONSTRAINT FK_SK_CATEGORY   FOREIGN KEY (category_id) REFERENCES CARD_CATEGORIES(category_id),
    CONSTRAINT FK_SK_CREATED_BY FOREIGN KEY (created_by)  REFERENCES ADMIN_USERS(admin_id),
    CONSTRAINT FK_SK_UPDATED_BY FOREIGN KEY (updated_by)  REFERENCES ADMIN_USERS(admin_id)
);
COMMENT ON TABLE SEARCH_KEYWORDS IS '관리자 등록 추천 검색 키워드';

-- 44. CARD_KEYWORDS
CREATE TABLE CARD_KEYWORDS (
    card_keyword_id  NUMBER(10)  PRIMARY KEY,
    card_id          NUMBER(10)  NOT NULL,
    keyword_id       NUMBER(10)  NOT NULL,
    created_at       TIMESTAMP   DEFAULT SYSTIMESTAMP NOT NULL,
    created_by       NUMBER(10),
    deleted_yn       CHAR(1)     DEFAULT 'N' NOT NULL CHECK (deleted_yn IN ('Y','N')),
    deleted_at       TIMESTAMP,
    CONSTRAINT FK_CK_CARD         FOREIGN KEY (card_id)    REFERENCES CARDS(card_id),
    CONSTRAINT FK_CK_KEYWORD      FOREIGN KEY (keyword_id) REFERENCES SEARCH_KEYWORDS(keyword_id),
    CONSTRAINT FK_CK_CREATED_BY   FOREIGN KEY (created_by) REFERENCES ADMIN_USERS(admin_id),
    CONSTRAINT UK_CK_CARD_KEYWORD UNIQUE(card_id, keyword_id)
);
COMMENT ON TABLE CARD_KEYWORDS IS '카드 ↔ 검색 키워드 매핑';

-- 45. SEARCH_LOGS
CREATE TABLE SEARCH_LOGS (
    search_log_id       NUMBER(10)     PRIMARY KEY,
    user_id             NUMBER(10),
    keyword_raw         VARCHAR2(200)  NOT NULL,
    matched_keyword_id  NUMBER(10),
    result_count        NUMBER(10),
    search_at           TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    ip_address          VARCHAR2(100),
    device_info         VARCHAR2(500),
    CONSTRAINT FK_SL_USER            FOREIGN KEY (user_id)            REFERENCES USERS(user_id),
    CONSTRAINT FK_SL_MATCHED_KEYWORD FOREIGN KEY (matched_keyword_id) REFERENCES SEARCH_KEYWORDS(keyword_id)
);
COMMENT ON TABLE SEARCH_LOGS IS '고객 검색 로그';

-- 46. USER_SPENDING_PATTERNS
CREATE TABLE USER_SPENDING_PATTERNS (
    pattern_id      NUMBER(10)     PRIMARY KEY,
    user_id         NUMBER(10)     NOT NULL,
    category_id     NUMBER(10)     NOT NULL,
    monthly_amount  NUMBER(10)     NOT NULL CHECK (monthly_amount >= 0),
    source          VARCHAR2(10)   NOT NULL CHECK (source IN ('MANUAL','AUTO')),
    updated_at      DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_USP_USER   FOREIGN KEY (user_id)    REFERENCES USERS(user_id),
    CONSTRAINT FK_USP_CATEGO FOREIGN KEY (category_id) REFERENCES CARD_CATEGORIES(category_id)
);
COMMENT ON TABLE  USER_SPENDING_PATTERNS        IS '사용자 월별 카테고리 소비패턴';
COMMENT ON COLUMN USER_SPENDING_PATTERNS.source IS 'MANUAL=직접입력 / AUTO=결제기반 자동분류';

-- 47. AI_CHAT_LOGS
CREATE TABLE AI_CHAT_LOGS (
    chat_id     NUMBER(10)     PRIMARY KEY,
    user_id     NUMBER(10)     NULL,
    session_id  VARCHAR2(100)  NOT NULL,
    user_input  CLOB           NOT NULL,
    ai_response CLOB           NOT NULL,
    created_at  DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_CHAT_USER FOREIGN KEY (user_id) REFERENCES USERS(user_id)
);
COMMENT ON TABLE AI_CHAT_LOGS IS '챗봇 대화 로그 (비로그인 허용 — user_id NULL 가능)';

-- EVENT_LOGS (부모 — 이벤트 로그 슈퍼타입)
CREATE TABLE EVENT_LOGS (
    log_id        NUMBER(10)     PRIMARY KEY,
    event_type    VARCHAR2(100)  NOT NULL,
    event_status  VARCHAR2(200)  NOT NULL,
    user_id       NUMBER(10),
    request_ip    VARCHAR2(50),
    duration_ms   NUMBER(10),
    created_at    TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_EVLOG_USER FOREIGN KEY (user_id) REFERENCES USERS(user_id)
);
COMMENT ON TABLE EVENT_LOGS IS '이벤트 로그 부모 테이블. CARD/TERMS/CHAT 이벤트를 자식에서 상세화';

-- CARD_EVENT_LOGS (카드 이벤트 자식)
CREATE TABLE CARD_EVENT_LOGS (
    log_id        NUMBER(10)     PRIMARY KEY,
    card_id       VARCHAR2(20),
    action_detail VARCHAR2(200),
    result_code   VARCHAR2(100),
    error_message VARCHAR2(2000),
    CONSTRAINT FK_CARD_EVLOG FOREIGN KEY (log_id) REFERENCES EVENT_LOGS(log_id)
);
COMMENT ON TABLE CARD_EVENT_LOGS IS '카드 관련 이벤트 상세';

-- TERMS_EVENT_LOGS (약관 이벤트 자식)
CREATE TABLE TERMS_EVENT_LOGS (
    log_id        NUMBER(10)     PRIMARY KEY,
    terms_id      NUMBER(10),
    action_detail VARCHAR2(100),
    error_message VARCHAR2(2000),
    CONSTRAINT FK_TERMS_EVLOG FOREIGN KEY (log_id) REFERENCES EVENT_LOGS(log_id)
);
COMMENT ON TABLE TERMS_EVENT_LOGS IS '약관 관련 이벤트 상세';

-- CHAT_EVENT_LOGS (챗봇 이벤트 자식)
CREATE TABLE CHAT_EVENT_LOGS (
    log_id           NUMBER(10)     PRIMARY KEY,
    session_id       VARCHAR2(100),
    query_text       VARCHAR2(1000),
    qdrant_hit_count NUMBER(10),
    top_score        NUMBER(5,4),
    used_fallback    CHAR(1)        DEFAULT 'N',
    error_message    VARCHAR2(2000),
    CONSTRAINT FK_CHAT_EVLOG FOREIGN KEY (log_id) REFERENCES EVENT_LOGS(log_id)
);
COMMENT ON TABLE CHAT_EVENT_LOGS IS '챗봇 이벤트 상세 (Qdrant 검색 결과 포함)';

-- USER_ACTIVITY_LOG (사용자 행위 이력 — 삭제·수정 불가)
CREATE TABLE USER_ACTIVITY_LOG (
    activity_id  NUMBER(15)    PRIMARY KEY,
    user_id      NUMBER(10),
    action       VARCHAR2(60)  NOT NULL,
    result       CHAR(1)       NOT NULL CHECK (result IN ('S','F')),
    target_id    VARCHAR2(100),
    detail       VARCHAR2(2000),
    client_ip    VARCHAR2(45),
    request_uri  VARCHAR2(500),
    occurred_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);
COMMENT ON TABLE  USER_ACTIVITY_LOG           IS '사용자 행위 이력 (삭제·수정 불가)';
COMMENT ON COLUMN USER_ACTIVITY_LOG.action    IS 'CARD_APPLY_APPLY / TERMS_AGREE / AUTH_PASSWORD_CHANGE 등 category_action 형태';
COMMENT ON COLUMN USER_ACTIVITY_LOG.result    IS 'S=SUCCESS, F=FAILURE';
COMMENT ON COLUMN USER_ACTIVITY_LOG.target_id IS '대상 리소스 ID (카드ID, 약관ID 등 범용 문자열)';

-- ADMIN_ACTIVITY_LOG (관리자 행위 이력 — 삭제·수정 불가)
CREATE TABLE ADMIN_ACTIVITY_LOG (
    activity_id  NUMBER(15)    PRIMARY KEY,
    admin_id     NUMBER(10)    NOT NULL,
    action       VARCHAR2(60)  NOT NULL,
    result       CHAR(1)       NOT NULL CHECK (result IN ('S','F')),
    target_id    VARCHAR2(100),
    detail       VARCHAR2(2000),
    client_ip    VARCHAR2(45),
    request_uri  VARCHAR2(500),
    occurred_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);
COMMENT ON TABLE  ADMIN_ACTIVITY_LOG           IS '관리자 행위 이력 (삭제·수정 불가)';
COMMENT ON COLUMN ADMIN_ACTIVITY_LOG.action    IS 'CARD_CREATE / CARD_APPROVAL_APPROVE / ADMIN_USER_STATUS_CHANGE 등';
COMMENT ON COLUMN ADMIN_ACTIVITY_LOG.result    IS 'S=SUCCESS, F=FAILURE';
COMMENT ON COLUMN ADMIN_ACTIVITY_LOG.target_id IS '대상 리소스 ID (카드ID, 신청ID, 유저ID 등 범용 문자열)';


-- ── 트리거 ────────────────────────────────────────────────────────
CREATE OR REPLACE TRIGGER TRG_FILE_UPLOADS_BI
BEFORE INSERT ON FILE_UPLOADS FOR EACH ROW WHEN (NEW.file_id IS NULL)
BEGIN :NEW.file_id := SEQ_FILE_UPLOADS.NEXTVAL; END TRG_FILE_UPLOADS_BI;
/

CREATE OR REPLACE TRIGGER TRG_SEARCH_KEYWORDS_BI
BEFORE INSERT ON SEARCH_KEYWORDS FOR EACH ROW WHEN (NEW.keyword_id IS NULL)
BEGIN :NEW.keyword_id := SEQ_SEARCH_KEYWORDS.NEXTVAL; END TRG_SEARCH_KEYWORDS_BI;
/

CREATE OR REPLACE TRIGGER TRG_CARD_KEYWORDS_BI
BEFORE INSERT ON CARD_KEYWORDS FOR EACH ROW WHEN (NEW.card_keyword_id IS NULL)
BEGIN :NEW.card_keyword_id := SEQ_CARD_KEYWORDS.NEXTVAL; END TRG_CARD_KEYWORDS_BI;
/

CREATE OR REPLACE TRIGGER TRG_SEARCH_LOGS_BI
BEFORE INSERT ON SEARCH_LOGS FOR EACH ROW WHEN (NEW.search_log_id IS NULL)
BEGIN :NEW.search_log_id := SEQ_SEARCH_LOGS.NEXTVAL; END TRG_SEARCH_LOGS_BI;
/

CREATE OR REPLACE TRIGGER TRG_USER_SPENDING_BI
BEFORE INSERT ON USER_SPENDING_PATTERNS FOR EACH ROW WHEN (NEW.pattern_id IS NULL)
BEGIN :NEW.pattern_id := SEQ_USER_SPENDING_PATTERNS.NEXTVAL; END TRG_USER_SPENDING_BI;
/

CREATE OR REPLACE TRIGGER TRG_AI_CHAT_LOGS_BI
BEFORE INSERT ON AI_CHAT_LOGS FOR EACH ROW WHEN (NEW.chat_id IS NULL)
BEGIN :NEW.chat_id := SEQ_AI_CHAT_LOGS.NEXTVAL; END TRG_AI_CHAT_LOGS_BI;
/

CREATE OR REPLACE TRIGGER TRG_EVENT_LOGS_BI
BEFORE INSERT ON EVENT_LOGS FOR EACH ROW WHEN (NEW.log_id IS NULL)
BEGIN :NEW.log_id := SEQ_EVENT_LOGS.NEXTVAL; END TRG_EVENT_LOGS_BI;
/

-- USER_ACTIVITY_LOG — 채번 + 무결성 보장
CREATE OR REPLACE TRIGGER TRG_USER_ACTIVITY_LOG_BI
BEFORE INSERT ON USER_ACTIVITY_LOG FOR EACH ROW WHEN (NEW.activity_id IS NULL)
BEGIN :NEW.activity_id := SEQ_USER_ACTIVITY_LOG.NEXTVAL; END TRG_USER_ACTIVITY_LOG_BI;
/
CREATE OR REPLACE TRIGGER TRG_USER_ACTIVITY_LOG_NO_DEL
BEFORE DELETE ON USER_ACTIVITY_LOG FOR EACH ROW
BEGIN RAISE_APPLICATION_ERROR(-20110, '[USER_ACTIVITY_LOG] 행위 로그는 삭제할 수 없습니다.'); END;
/
CREATE OR REPLACE TRIGGER TRG_USER_ACTIVITY_LOG_NO_UPD
BEFORE UPDATE ON USER_ACTIVITY_LOG FOR EACH ROW
BEGIN RAISE_APPLICATION_ERROR(-20111, '[USER_ACTIVITY_LOG] 행위 로그는 수정할 수 없습니다.'); END;
/

-- ADMIN_ACTIVITY_LOG — 채번 + 무결성 보장
CREATE OR REPLACE TRIGGER TRG_ADMIN_ACTIVITY_LOG_BI
BEFORE INSERT ON ADMIN_ACTIVITY_LOG FOR EACH ROW WHEN (NEW.activity_id IS NULL)
BEGIN :NEW.activity_id := SEQ_ADMIN_ACTIVITY_LOG.NEXTVAL; END TRG_ADMIN_ACTIVITY_LOG_BI;
/
CREATE OR REPLACE TRIGGER TRG_ADMIN_ACTIVITY_LOG_NO_DEL
BEFORE DELETE ON ADMIN_ACTIVITY_LOG FOR EACH ROW
BEGIN RAISE_APPLICATION_ERROR(-20120, '[ADMIN_ACTIVITY_LOG] 행위 로그는 삭제할 수 없습니다.'); END;
/
CREATE OR REPLACE TRIGGER TRG_ADMIN_ACTIVITY_LOG_NO_UPD
BEFORE UPDATE ON ADMIN_ACTIVITY_LOG FOR EACH ROW
BEGIN RAISE_APPLICATION_ERROR(-20121, '[ADMIN_ACTIVITY_LOG] 행위 로그는 수정할 수 없습니다.'); END;
/


-- ── 인덱스 ────────────────────────────────────────────────────────
CREATE INDEX IDX_FILE_UPLOADS_REF   ON FILE_UPLOADS(ref_id);
CREATE INDEX IDX_SEARCH_KW_USE      ON SEARCH_KEYWORDS(use_yn);
CREATE INDEX IDX_SEARCH_KW_ORDER    ON SEARCH_KEYWORDS(display_order);
CREATE INDEX IDX_CARD_KW_CARD       ON CARD_KEYWORDS(card_id);
CREATE INDEX IDX_CARD_KW_KW         ON CARD_KEYWORDS(keyword_id);
CREATE INDEX IDX_SEARCH_LOGS_DATE   ON SEARCH_LOGS(search_at);
CREATE INDEX IDX_SEARCH_LOGS_USER   ON SEARCH_LOGS(user_id);
CREATE INDEX IDX_SPEND_USER         ON USER_SPENDING_PATTERNS(user_id);
CREATE INDEX IDX_SPEND_CAT          ON USER_SPENDING_PATTERNS(category_id);
CREATE INDEX IDX_AI_CHAT_SESS       ON AI_CHAT_LOGS(session_id);
CREATE INDEX IDX_AI_CHAT_USER       ON AI_CHAT_LOGS(user_id);
CREATE INDEX IDX_USER_ACT_USER      ON USER_ACTIVITY_LOG(user_id, occurred_at DESC);
CREATE INDEX IDX_USER_ACT_ACT       ON USER_ACTIVITY_LOG(action, occurred_at DESC);
CREATE INDEX IDX_USER_ACT_RES       ON USER_ACTIVITY_LOG(result, occurred_at DESC);
CREATE INDEX IDX_ADMIN_ACT_ADMIN    ON ADMIN_ACTIVITY_LOG(admin_id, occurred_at DESC);
CREATE INDEX IDX_ADMIN_ACT_ACT      ON ADMIN_ACTIVITY_LOG(action,   occurred_at DESC);
CREATE INDEX IDX_ADMIN_ACT_RES      ON ADMIN_ACTIVITY_LOG(result,   occurred_at DESC);


COMMIT;
