# Load local settings (application-local.properties)
debug=true
spring.profiles.active=local

spring.application.name=BNKcard

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

mybatis.mapper-locations=classpath:mappers/**/*.xml
mybatis.type-aliases-package=com.bnk.domain.**.model
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.default-statement-timeout=30
mybatis.configuration.cache-enabled=false

server.port=8088
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true
app.base-url=http://localhost:8088

jwt.secret=
jwt.access-expiration=72000000
jwt.refresh-expiration=604800000

aes.secret-key=
cors.allowed-origins=http://localhost:8088,http://localhost:8089,http://localhost:3000

cookie.secure=false

# Logging
logging.level.com.bnk=DEBUG
logging.level.org.mybatis=DEBUG

# Vectorstore
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=bnkcard
spring.ai.vectorstore.qdrant.use-tls=false
spring.ai.vectorstore.qdrant.initialize-schema=true

# OCI Object Storage
oci.tenancy-id=
oci.user-id=
oci.fingerprint=
oci.private-key-path=
oci.region=
oci.bucket-name=
oci.namespace=

#geminiapi
spring.ai.google.genai.api-key=
spring.ai.google.genai.project-id=
spring.ai.google.genai.chat.model=gemini-2.5-flash
spring.ai.google.genai.embedding.api-key=
spring.ai.google.genai.embedding.project-id=
ai.enabled=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.username=
spring.mail.password=
mail.from.name=BNK카드
file.upload-dir=C:/upload

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=300000

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB
spring.servlet.multipart.enabled=true
